name: Rust Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo Build
        run: cargo build

      - name: Cargo Test
        run: cargo test

      - name: Cargo Benchmark
        run: cargo bench

      - name: Cargo Doc
        run: cargo doc