name: Rust Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - name: Cargo Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo Build
        run: cargo build

      - name: Cargo Test
        run: cargo test

      - name: Cargo Benchmark
        run: cargo bench

      - name: Cargo Doc
        run: cargo doc