name: Rust Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - name: Cargo Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#example-using-multiple-restore-keys
          restore-keys: |
            ${{ runner.os }}-cargo-
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo Build
        run: cargo build

      - name: Cargo Test
        run: cargo test

      - name: Cargo Benchmark
        run: cargo bench

      - name: Cargo Doc
        run: cargo doc